### ISSUE TITLE
Sometimes getting unnecessary extra info in result of 'map -l' command

### ISSUE THREAD

**Issue by samsonbek** [subutai-io/agent#118]
When executing `subutai map -l` command, sometimes get extra `runtime/cgo: ` info in output.
This happens very rare. And if that command is executed again immediately, this extra info is not repeated.

```subutai@rh1494429566:~$ sudo subutai list -i
NAME			STATE	IP		Interface
----			-----	--		---------
management		RUNNING	10.10.10.1	eth0
tp4-c1-nLC-100-4	RUNNING	172.31.31.4	eth0
subutai@rh1494429566:~$ 
subutai@rh1494429566:~$ sudo subutai map -l
runtime/cgo: tcp	3380	172.31.31.4:80
tcp	8086	10.10.10.1:8086
tcp	8443	10.10.10.1:8443
tcp	8444	10.10.10.1:8444
subutai@rh1494429566:~$ 
subutai@rh1494429566:~$ sudo subutai map -l
tcp	3380	172.31.31.4:80
tcp	8086	10.10.10.1:8086
tcp	8443	10.10.10.1:8443
tcp	8444	10.10.10.1:8444
subutai@rh1494429566:~$ 
```
Agent version is:
```subutai@rh1494429566:~$ sudo subutai -v
Subutai version 4.0.16-SNAPSHOT dev/d9603c3663afdf4f595dfbc38d4ea6dfe40c29c4
```

**Comment by tzununbekov** [comment]
Managed to gather a bit more information about this issue:
```
...
7111 Incorrect output:
runtime/cgo: pthread_create failed: Resource temporarily unavailable
...

Total: 10000
With unexpected output: 2
```
Looks like the cause of such message may be in kernel/systemd resource limitations. Average frequency of this error is up to 3 times out of 10000 calls, but it might depend on the system environment.

**Comment by tzununbekov** [comment]
Looks like updates in another system components reduced resource usage by agent or increased its limitation so this unexpected output stopped to appear in my tests at all. Issue is closed for now, but kept in mind.
