### ISSUE TITLE
"Fingeprint" setting in agent.gcfg does not work

### ISSUE THREAD

**Issue by Dilshat** [subutai-io/agent#136]
How to reproduce:
Create and VM without importing management
Edit agent.gcfg file and set **Fingerprint** to peer id(fingeprint)
Restart agent

Expected behavior: Agent should send registration request to the Console
Actual behavior: Agent sends registration request to the Console only if also the **Host** parameter is set to peer ip

**Comment by soffokl** [comment]
This issue is not reproducible on the latest version of the Subutai Agent.
