### ISSUE TITLE
Sometimes `subutai export` command breaks

### ISSUE THREAD

**Issue by p1gmale0n** [subutai-io/agent#16]
```
time="2016-11-10 13:05:06" level=fatal msg="Sending delta /mnt/lib/lxc/tmpdir/management-subutai-template_4.0.7-dev_amd64/deltas/var.delta, exit status 1"
```

**Comment by soffokl** [comment]
After deep investigation we have found that intensive creating/removing files, snapshots give problems with sending BTRFS subvolume. As a workaround now we are exporting template from snapshoted copies of subvolumes. That gives us fresh copy, and looks like it solves problem.
