### ISSUE TITLE
Environment building fail with 'panic runtime error'

### ISSUE THREAD

**Issue by samsonbek** [subutai-io/agent#179]
I have latest production peer with two RHs. 
![image](https://user-images.githubusercontent.com/4163679/31769747-b5e46e3a-b4f6-11e7-978e-6fab31bf2b3c.png)

![image](https://user-images.githubusercontent.com/4163679/31769936-6cc23dd0-b4f7-11e7-9d93-765e0c3a7b87.png)

MH:
![image](https://user-images.githubusercontent.com/4163679/31769773-ce2ebee6-b4f6-11e7-94c4-789f25bf5e09.png)

RH:
![image](https://user-images.githubusercontent.com/4163679/31769800-ef42b4d4-b4f6-11e7-9ace-a9903b170231.png)

Tried to create environment via Hub, with one `apache` and one `ubuntu16` template, placed both of them to MH.
![image](https://user-images.githubusercontent.com/4163679/31769970-906f295a-b4f7-11e7-8df9-5eb1dffbf418.png)

Env. build failed with:
![image](https://user-images.githubusercontent.com/4163679/31769867-2fe7fc24-b4f7-11e7-8b9d-08757235c134.png)
[karaflogs2017-10-19 17-47-13.txt.tar.gz](https://github.com/subutai-io/agent/files/1398217/karaflogs2017-10-19.17-47-13.txt.tar.gz)

**Comment by akarasulu** [comment]
@Dilshat please take a look at these logs and let's determine if this is an ss or agent issue.

**Comment by soffokl** [comment]
Fixed
