### ISSUE TITLE
OS info of resource host

### ISSUE THREAD

**Issue by samsonbek** [subutai-io/agent#183]
It would be nice to have info about OS of each RH. This info should be sent to Hub by Subutai Console, along with RH information. I think it will be useful, to see on which OS(versions) users install RH:
ubuntu server, ubuntu core, 16, 17, debian, mint, etc.

**Comment by Dilshat** [comment]
On some installations ***release** files contain only "PRETTY_NAME" param which can be used if "DISTRIB_DESCRIPTION"is missing
