### ISSUE TITLE
subutai update should display download information

### ISSUE THREAD

**Issue by akarasulu** [subutai-io/agent#188]
Presently `subutai update rh` does not show any download information as does the management import. This makes the user think something is hung to control-c the command especially when the network is slow. 

```
root@subutai:~# subutai update rh
^C
root@subutai:~# subutai update rh
FATA[2017-11-03 05:30:38] Updating RH snap, exit status 1              
root@subutai:~# subutai -d update rh
DEBU[2017-11-03 05:31:19] Init lock rh.update                          
DEBU[2017-11-03 05:31:19] Locking file rh.update                       
FATA[2017-11-03 05:31:22] Updating RH snap, exit status 1              
root@subutai:~# snap
snap     snapctl  
root@subutai:~# snap refresh subutai --beta --devmode
error: cannot refresh "subutai": snap "subutai" has changes in progress
```

**Comment by Almansherov** [comment]
Created a peer and updated the rh:

[Agent.mp4.tar.gz](https://github.com/subutai-io/agent/files/2356800/Agent.mp4.tar.gz)

Fixed

**Comment by Dilshat** [comment]
How to test:
On RH with update available, run `subutai update rh`
command should output progress of update

**Comment by kurmanbekova6** [comment]
1. Logged in to console.
2. Updated rh

Fixed in Master. This issue also was checked by @Almansherov . You can see comment above.

**Comment by kurmanbekova6** [comment]
![screenshot_9](https://user-images.githubusercontent.com/9501291/45815780-82149400-bcfb-11e8-9ae6-b2c478850ec3.png)
