### ISSUE TITLE
Odd behavior with self-signed certificate on CDN Cache node

### ISSUE THREAD

**Issue by akarasulu** [subutai-io/agent#196]
I was experimenting around with setting up a cache node according to the documentation for it [here](https://github.com/subutai-io/gorjun/wiki/Nginx-cache). I followed the directions using a self-signed certificate. I then tried importing management on a fresh new resource host and it failed a few times complaining about the unknown authority then it started working after a few tries.

> subutai@stretch:~$ sudo /snap/bin/subutai import -v management
INFO[2017-11-11 18:03:39] Importing                                    
ERRO[2017-11-11 18:03:39] Retrieving id, get: https://cdn.subut.ai:8338/kurjun/rest/template/info?name=&token=, Get https://cdn.subut.ai:8338/kurjun/rest/template/info?name=&token=: x509: certificate signed by unknown authority 
subutai@stretch:~$ sudo /snap/bin/subutai import -v management
INFO[2017-11-11 18:04:47] Importing                                    
ERRO[2017-11-11 18:04:47] Retrieving id, get: https://cdn.subut.ai:8338/kurjun/rest/template/info?name=&token=, Get https://cdn.subut.ai:8338/kurjun/rest/template/info?name=&token=: x509: certificate signed by unknown authority 
subutai@stretch:~$ sudo /snap/bin/subutai import -v management
INFO[2017-11-11 18:05:33] Importing                                    
INFO[2017-11-11 18:05:34] Version: 4.0.0                               
ERRO[2017-11-11 18:05:34] Template is not signed                       
subutai@stretch:~$ sudo /snap/bin/subutai import -v management
INFO[2017-11-11 18:05:37] Importing                                    
INFO[2017-11-11 18:05:38] Version: 4.0.0                               
ERRO[2017-11-11 18:05:38] Template is not signed                       
subutai@stretch:~$ sudo /snap/bin/subutai import  management
INFO[2017-11-11 18:05:45] Importing management                         
INFO[2017-11-11 18:05:45] Version: 6.1.3                               
INFO[2017-11-11 18:05:46] Template's owner signature verified          
INFO[2017-11-11 18:05:46] Downloading management                       

What's going on here? Why would this happen? How could it happen? 

Very strange.

**Comment by akarasulu** [comment]
Also note the version bump that occurred: First 4.0.0, then 6.1.3.

**Comment by soffokl** [comment]
`-v` option should specify version desired template. But in your example, it set as `management` and template name is set to empty string

**Comment by Dilshat** [comment]
Just in case you wanted debug option it is **-d**

**Comment by akarasulu** [comment]
Ok this is obviously some human error: I meant to do a -d rather than a -v. Thanks.
