### ISSUE TITLE
Enable Bash Completion

### ISSUE THREAD

**Issue by liquuid** [subutai-io/agent#208]
Reading https://github.com/urfave/cli#examples I found that is possible enable Bash Completion. If enable it is not a problem I can do it later.

**Comment by Dilshat** [comment]
please see this https://github.com/subutai-io/snap/blob/master/extras/etc/bash_completion

**Comment by liquuid** [comment]
Hum, seems all pieces on place, but did not worked in my env.

**Comment by Dilshat** [comment]
Yes this works partially. We need to fix this

**Comment by liquuid** [comment]
I've made some tests and can't find a way to install extras/etc/bash_completion into proper place ( /etc/bash_completion.d/ ) using snapcraft. 

Is possible to subutai cli check if bash_completion in host is enabled, if yes create a symbolic link in /etc/bash_completion.d/ pointing to snap bundled bash_completion file. I think it's a very invasive approach to whom run subutai in a non-virtualized enviroment. But works like a charm.

What you think ?

**Comment by liquuid** [comment]
I've solved it with a tiny modification on snapcraft.yml on snap repository.

https://github.com/liquuid/snap/commit/23a3a206b53bdaf6a36e3ef551d22c478511b037

But I think bash_completion script must exists only in agent repository.

**Comment by Dilshat** [comment]
Seems bash completion does not work. After merging changes we didn't notice changes except completion for **subutai** word.

**Comment by liquuid** [comment]
Hum, I will check this

**Comment by liquuid** [comment]
Thats strange, it worked here.  I'm using these snapcraft.yaml https://gist.github.com/liquuid/1436d6c27d2136e99cc212ae897a35e4  and snap, agent, p2p in master branch.

I think create a snap with a tag on subutai command i (like subutai-dev or subutai-master)  break the bash_completion script, I can't find a way to enable bash completion in this case yet.

**Comment by Dilshat** [comment]
not working

**Comment by marcoarthur** [comment]
@Dilshat . I tested here in my env the following way: ./configure then run the snapcraft {dev,master} then installed in my vm the tar ball generated. After that I sourced /etc/bash_completion generated . I couldn't get other automatic way to source it.

**Comment by Dilshat** [comment]
If I understand correctly
```
root@rh:~# subutai
subutai          subutai-dev      subutai-dev.p2p  
root@rh:~# subutai
subutai          subutai-dev      subutai-dev.p2p  
root@rh:~# subutai-dev m
No help topic for 'm'
root@rh:~# subutai-dev l
``

**Comment by akarasulu** [comment]
Just a question as a user. I would love the bash completion to complete candidate container arguments because some of those container names are well ... a bitch to type out. Does the bash completion do that being aware of container name context?

**Comment by marcoarthur** [comment]
@Dilshat yes, that should work, We saw here I made a simple mistake when sending my patch, really forget to include a ? (question mark on the end of a pattern) I tested with a different pattern and send other in other words. But I'll correct that. @akarasulu Yes it is possible too. It runs the command to list the containers when command is subjected to the container name. I'm correcting this error and sending a patch again.

**Comment by akarasulu** [comment]
Oh man being able to complete the container names would be so awesome!!!

**Comment by Dilshat** [comment]
Seems snap can not alias itself: even if we indicate [subutai] in snapcraft.yaml it does not work.
Yeah if we do (for master peer):
```
snap alias subutai-master subutai
source /snap/subutai-master/current/etc/bash_completion.tmpl
````
then completion works for first argument after subutai like subutai list, subutai map
Need to add sublevels and execute the commands above by vagrant plugin
@jadilet @akarasulu @marcoarthur @liquuid

**Comment by amol4anoff** [comment]
@Dilshat how to test?

**Comment by Dilshat** [comment]
Released
