### ISSUE TITLE
Document the private Agent REST API

### ISSUE THREAD

**Issue by akarasulu** [subutai-io/agent#214]
We need to document the private Agent API that is being used by the management console to interface with the Resource Host.

**Comment by Dilshat** [comment]
https://github.com/subutai-io/agent/wiki/Private-REST-API

**Comment by akarasulu** [comment]
All are GET operations?

**Comment by Dilshat** [comment]
Will update soon

**Comment by akarasulu** [comment]
No worries I guess the swagger specification will handle all this. Hence why we want swagger everywhere.

**Comment by liquuid** [comment]
https://github.com/subutai-io/agent/wiki/Auto-generated-REST-API

**Comment by amol4anoff** [comment]
I see detailed info on REST API here - https://github.com/subutai-io/agent/wiki/Auto-generated-REST-API-Documentation
