### ISSUE TITLE
Create a public swagger specified REST API for automation

### ISSUE THREAD

**Issue by akarasulu** [subutai-io/agent#215]
It's becoming apparent that we need to start to do certain things for automation to work with the RH. First thing, we need is to be able to lookup the ID of the RH to automate RH registration and unregistration. See https://github.com/subutai-io/base/wiki/%5BAutomation%5D:-%5BUn%5DRegister-RH-from-Peer.

Just querying for certain things are needed at first and we can add this over time on an as needed agile basis.

**Comment by Dilshat** [comment]
Closing as its Pipeline is Done
