### ISSUE TITLE
Testing port mapping on hub production, cant access container from domain

### ISSUE THREAD

**Issue by amol4anoff** [subutai-io/agent#218]
![ttt](https://user-images.githubusercontent.com/33647491/33699346-c4295494-db3c-11e7-88f3-9b62b5a46ee5.png)
I created env, tested port mapping, set up all there. Im on win10, chrome 62. Then i reserved domian and tried to access container through domain, but it opened nginx error on the new page. Template is Ubuntu16
![sss](https://user-images.githubusercontent.com/33647491/33699344-c0113782-db3c-11e7-9ca2-fd4789ba9f22.png)

**Comment by Dilshat** [comment]
@amol4anoff you need to use a template with some web app inside like **apache** template.
The mapping worked correctly but there is not backend listening to user requests and nginx displays error page
