### ISSUE TITLE
[PROD] Environment becomes Unhealthy even with online peer

### ISSUE THREAD

**Issue by Shahrizada** [subutai-io/agent#241]
![screen shot 2018-01-06 at 16 32 35](https://user-images.githubusercontent.com/31571523/34638929-1bf45a36-f300-11e7-8c2f-62ba19b3373e.png)
[karaflogs2018-01-06 16_39_17.txt](https://github.com/subutai-io/agent/files/1608699/karaflogs2018-01-06.16_39_17.txt)

![screen shot 2018-01-06 at 16 31 48](https://user-images.githubusercontent.com/31571523/34638926-080e388e-f300-11e7-9fab-8ac3f05ab436.png)

**Comment by Shahrizada** [comment]
[karaflogs2018-01-06 16_39_17.txt](https://github.com/subutai-io/agent/files/1608701/karaflogs2018-01-06.16_39_17.txt)

**Comment by Shahrizada** [comment]
Environments came back Healthy in aprxmtly 10 min.

**Comment by Dilshat** [comment]
Seems there was a temporary network glitch when agent was not reachable from Console
Next time please attach agent logs by executing on RH:

`journalctl --since "10 minutes ago" | grep agent`

where 10 minutes is approximately when problem occured

**Comment by Shahrizada** [comment]
ok, got it. Thanks
