### ISSUE TITLE
Completely dead peer VM with lots of crazy syslog messages

### ISSUE THREAD

**Issue by akarasulu** [subutai-io/agent#254]
Here's a syslog of a VM that just died with subutai master on it, and on the same physical machine the prod VM was perfect ... I could not access the console of the VM via VirtualBox that died, nor could I ssh to it anymore. There are several networking error messages in the syslog that should be looked at. I am gziping and sending the syslog.

Time wise you can locate the time at which syslog shows the last reboot. This was after HARD power cycling the VM.

Attached Syslog: 
[syslog.gz](https://github.com/subutai-io/agent/files/1618905/syslog.gz)

Here's the p2p, agent and karaf logs:

[p2p.log.gz](https://github.com/subutai-io/agent/files/1618927/p2p.log.gz)

[agent.log.gz](https://github.com/subutai-io/agent/files/1618933/agent.log.gz)

[karaf.log.gz](https://github.com/subutai-io/agent/files/1618914/karaf.log.gz)

**Comment by Dilshat** [comment]
@akarasulu please test on latest peer if this issue is reproduced

**Comment by akarasulu** [comment]
This seems like a fluke due to some vbox issue. I'll close this for now. If it appears again with the new vagrant boxes we can reopen and look at this more carefully.
