### ISSUE TITLE
Confusing output from subutai cli

### ISSUE THREAD

**Issue by lbthomsen** [subutai-io/agent#275]
malta2417:~# subutai import debian
INFO[2018-01-19 11:55:44] Importing debian                             
INFO[2018-01-19 11:55:44] Version: 4.0.0                               
INFO[2018-01-19 11:55:46] CDN unreachable, retrying                    
INFO[2018-01-19 11:55:49] Template's owner signature verified          
INFO[2018-01-19 11:55:50] Unpacking template debian                    
INFO[2018-01-19 11:55:51] Installing template debian                   
malta2417:~# subutai destroy debian
WARN[2018-01-19 11:56:08] Deleting container metadata entry, bucket not found 
INFO[2018-01-19 11:56:08] debian not found. Please check if a container name is correct.

[7:56] 
malta2417:~# subutai list -t
TEMPLATE
--------
abdysamat-apache
accumulo
apache
debian-stretch
hadoop
master
mate-desktop
openjre16
oraclejava816
ubuntu16

Template is removed but the output from the subutai destroy command is confusing.

**Comment by Dilshat** [comment]
need to add a switch for destroy template like `subutai destroy -t debian`

**Comment by lbthomsen** [comment]
How about a -a (all or all that is not being used)

**Comment by Dilshat** [comment]
Fixed in 6.4.2
