### ISSUE TITLE
subutai cli without parameters should return usage instruction

### ISSUE THREAD

**Issue by liquuid** [subutai-io/agent#296]
```
root@subutai:/var/snap/subutai/common/lxc/backups# subutai config
FATA[2018-01-25 17:01:21] Reading config, open /var/snap/subutai/common/lxc//config: no such file or directory 
root@subutai:/var/snap/
```

```
root@subutai:/var/snap/subutai/common/lxc/backups# subutai demote
ERRO[2018-01-25 17:14:03] Container  is not a template    
```

**Comment by amol4anoff** [comment]
Good. Seems to be fixed:
subutai@subutai:/var/snap/subutai-master/common/lxc/backups$ sudo subutai-master config
NAME:
   subutai config - edit container config

USAGE:
   subutai config [command options] [arguments...]

OPTIONS:
   --operation value, -o value  <add|del> operation
   --key value, -k value        configuration key
   --value value, -v value      configuration value

and:
subutai@subutai:/var/snap/subutai-master/common/lxc/backups$ sudo subutai-master demote
NAME:
   subutai demote - demote Subutai container

USAGE:
   subutai demote [command options] [arguments...]

OPTIONS:
   --ipaddr value, -i value  IPv4 address, ie 192.168.1.1/24
   --vlan value, -v value    VLAN tag
