### ISSUE TITLE
Something wrong with cloud Google peer on masterhub

### ISSUE THREAD

**Issue by amol4anoff** [subutai-io/agent#306]
I'm using Google cloud peer -https://masterhub.subut.ai/peers/998
Keep trying and trying to turn it on, but nothing happens - it's frozen in that offline state.
Cannot access its console and get karaf logs.
Its state is RUNNING, but its offline on hub.

**Comment by Dilshat** [comment]
I can not access the peer, @samsonbek please see how we can turn it on so that we can ssh into it

**Comment by Dilshat** [comment]
the peer was borked. @amol4anoff  if happens again then please reopen
