### ISSUE TITLE
subutai clone without parameters import and clone a null name template

### ISSUE THREAD

**Issue by liquuid** [subutai-io/agent#334]
root@subutai:~# subutai clone
INFO[2018-02-06 11:28:56] CDN unreachable, retrying                    
INFO[2018-02-06 11:29:00] Importing                                    
INFO[2018-02-06 11:29:01] Version: 4.0.0                               
ERRO[2018-02-06 11:29:01] Template is not signed  

related to #296

**Comment by amol4anoff** [comment]
I have this output:

subutai@subutai:~$ sudo subutai-master clone
NAME:
   subutai clone - clone Subutai container

USAGE:
   subutai clone [command options] [arguments...]

OPTIONS:
   --env value, -e value     set environment id for container
   --ipaddr value, -i value  set container IP address and VLAN
   --token value, -t value   token to verify with MH
   --kurjun value, -k value  kurjun token to clone private and shared templates
   
subutai@subutai:~$
