### ISSUE TITLE
subutai import without parameters import  a null name template 

### ISSUE THREAD

**Issue by liquuid** [subutai-io/agent#335]
related to #296 

root@subutai:~# subutai import   
INFO[2018-02-06 12:13:55] CDN unreachable, retrying                    
INFO[2018-02-06 12:13:58] Importing                                    
INFO[2018-02-06 12:14:00] Version: 4.0.0                               
ERRO[2018-02-06 12:14:00] Template is not signed

**Comment by amol4anoff** [comment]
It returns instructions:
subutai@subutai:~$ sudo subutai-master import
NAME:
   subutai import - import Subutai template

USAGE:
   subutai import [command options] [arguments...]

OPTIONS:
   --token value, -t value  token to access private repo
   --local, -l              prefer to use local template archive
   
subutai@subutai:~$
