### ISSUE TITLE
Start management after reboot

### ISSUE THREAD

**Issue by efeefe** [subutai-io/agent#337]
In a box running Subutai Peer installed via snap on Ubuntu 16.04, management is not started after reboot. We had to start it manually using subutai start management. It should be started automatically.

**Comment by liquuid** [comment]
I think is related to https://github.com/subutai-io/snap/issues/224

**Comment by Dilshat** [comment]
please test with latest peer

**Comment by happyaron** [comment]
Should agent save container's running status and restart them upon reboot?

**Comment by Dilshat** [comment]
It already does that
