### ISSUE TITLE
Cleanup unused templates and archives

### ISSUE THREAD

**Issue by Dilshat** [subutai-io/agent#346]
After template import (installation) we should remove template archive to save space on disk.
Also we should remove unused templates that don't have child container instances (this operation should run only if there is no active import/clone operation to avoid removing template in-between its download and cloning)

**Comment by Dilshat** [comment]
the following commands will be added
subutai prune archives -  to remove template archive files
subutai prune templates - to remove unused templates, that do not have child container instances

**Comment by amol4anoff** [comment]
@Dilshat i ran that commands on peer:

subutai@subutai:~$ sudo subutai-master prune archives
subutai@subutai:~$ sudo subutai-master prune archives
subutai@subutai:~$ sudo subutai-master prune templates
INFO[2018-02-16 05:22:10] Destroying template ubuntu-xenial
