### ISSUE TITLE
Decrease CDN dependency of clone operation

### ISSUE THREAD

**Issue by Dilshat** [subutai-io/agent#350]
Currently agent requests CDN if clone with id instead of name of template is used.
However, import operation in most cases (except import with --local option) already stores id of template in local agent db. We need to decrease round-trips to CDN by looking up id in local db.

**Comment by amol4anoff** [comment]
Done:

subutai@subutai:~$ sudo subutai-master clone id:c0d9f79ca76a7eb7e9f0a4f8ed522585 Container-1-nWL-in7-2-3Bro
INFO[2018-02-16 10:08:28] Container-1-nWL-in7-2-3Bro started           
INFO[2018-02-16 10:08:28] Container-1-nWL-in7-2-3Bro with ID 9EF1BF687A772AE4FC72B821C466ED9B862307A2 successfully cloned 
subutai@subutai:~$
