### ISSUE TITLE
Review agent code to close file descriptors early

### ISSUE THREAD

**Issue by Dilshat** [subutai-io/agent#354]
Seems under heavy load, agent does not close FDs on time which results in `too many open files` error.
We need to review agent codebase and replace **defer** statements with early calls to Close() where possible

**Comment by Dilshat** [comment]
Might be useful http://craigwickesser.com/2015/01/golang-http-to-many-open-files/

**Comment by Dilshat** [comment]
The cause was 
```
Getting Management host GPG fingerprint, Get https://10.10.10.1:8443/rest/v1/security/keyman/getpublickeyfingerprint: dial tcp 10.10.10.1:8443: socket: too many open files
```

**Comment by amol4anoff** [comment]
Tested. Executed on RH:
subutai@subutai:~$ lsof -p `pgrep -f "subutai daemon"` | wc | tr -s ' ' | cut -d' ' -f2
5
subutai@subutai:~$ lsof -p `pgrep -f "subutai daemon"` | wc | tr -s ' ' | cut -d' ' -f2
5
subutai@subutai:~$ lsof -p `pgrep -f "subutai daemon"` | wc | tr -s ' ' | cut -d' ' -f2
5
subutai@subutai:~$ lsof -p `pgrep -f "subutai daemon"` | wc | tr -s ' ' | cut -d' ' -f2
5
subutai@subutai:~$ lsof -p `pgrep -f "subutai daemon"` | wc | tr -s ' ' | cut -d' ' -f2
5
subutai@subutai:~$ lsof -p `pgrep -f "subutai daemon"` | wc | tr -s ' ' | cut -d' ' -f2
5
subutai@subutai:~$
