### ISSUE TITLE
"subutai attach container command" does not work for a command with arguments

### ISSUE THREAD

**Issue by Dilshat** [subutai-io/agent#360]
`subutai attach container command` works only for a single command without arguments.

**Comment by Dilshat** [comment]
for command with arguments use this form:
`subutai attach foo "ls -l | grep home"`

**Comment by etursunbaev** [comment]
it works!

**Comment by akarasulu** [comment]
Yes please we cannot afford to get out of sync with documentation. It get's too painful to do mass changes later on. If you do not have docs you don't have a product. This is part of our core responsibility.

**Comment by Dilshat** [comment]
I was going to update after release, will do it now

**Comment by amol4anoff** [comment]
Done.
