### ISSUE TITLE
Enable XZ compression on templates, backups, export etc.

### ISSUE THREAD

**Issue by liquuid** [subutai-io/agent#369]
Just an idea based on my last personal disk space shortage :-D 

For example, I get a template from kurjun originally with 47M size. After re-compress with `xz -9`, 36M: 

```
liquuid@optdyn-ubuntu1604:~/teste$ ls -lh
total 83M
-rw-rw-r-- 1 liquuid liquuid 36M Fev 15 08:45 template2-test.tar.xz
-rw-rw-r-- 1 liquuid liquuid 47M Set 26 02:36 template-test.tar.gz

```

Do you think worth it ?

**Comment by Dilshat** [comment]
We will now periodically remove templates/archives

**Comment by liquuid** [comment]
Do you think adding a flag to export , backup and import cmd ( local file)  compressed with xz still a good idea ?

**Comment by Dilshat** [comment]
templates are removed periodically, and they are kept in `/var/cache` which is emptied regularly by system too
