### ISSUE TITLE
Renaming container led to "loose" data

### ISSUE THREAD

**Issue by etursunbaev** [subutai-io/agent#376]
Recently I tried to use CLI "Subutai rename old_name new_name "
And this command successfully renamed container. But inside container I lost data from /opt directory
In RH I see that data exists in correct path `/var/snap/subutai-dev/common/lxc/container/opt`
But inside container in /opt directory container does not see those data.

**Comment by Dilshat** [comment]
This command is to be removed. It leads to inconsistencies in operation.
Container names are system internal thing which is read only for users. Users should be able only to change hostnames.

**Comment by etursunbaev** [comment]
Ok, clear!
