### ISSUE TITLE
Strip whitespace when promoting/cloning a template

### ISSUE THREAD

**Issue by Dilshat** [subutai-io/agent#377]
Template and container names should not contain white space

**Comment by amol4anoff** [comment]
Seems to be fixed:
subutai@subutai:~$ sudo subutai-master import "let's talk"
ERRO[2018-02-23 07:34:39] Failed to get template info:  400 Bad Request 
subutai@subutai:~$

**Comment by amol4anoff** [comment]
subutai@subutai:~$ sudo subutai-master clone master "foo bar"
INFO[2018-02-23 07:50:53] foobar started                               
INFO[2018-02-23 07:50:53] foobar with ID 51F84858EFC9EA302E799B8D854D20C91401A0E4 successfully cloned 

Ok, done.
