### ISSUE TITLE
Support to multiple targets on subutai commands

### ISSUE THREAD

**Issue by liquuid** [subutai-io/agent#382]
I tried remove multiple containers at once without success

```
root@localhost:~# subutai destroy openjre16 teste-novo teste2 teste3  ubuntu16
INFO[2018-02-20 15:13:08] Destroying template openjre16                
INFO[2018-02-20 15:13:08] openjre16 is destroyed                       
root@localhost:~# 
```

I don't know if absence of this feature was intentional, if not, lets go solve this then :-D  

This enhancement should affected: 

import
destroy
backup
demote
promote
export
quota
restore
start
stop
update

anything else ?

**Comment by Dilshat** [comment]
We should be careful and check all commands if they lock the template/container before doing the operation.
For example `import` command locks on template name to avoid parallel imports of the same template.
The same should be done for most of the commands above.
I don't see any value in this improvement

**Comment by liquuid** [comment]
Yeah, there are several lock problems to care about.
I see value as heavy user of cli commands at general computing tasks and system management, docker allows it, snap, pacman, rm etc .  Despite subutai ansible module easily allow create recipes that ignores this cli limitation.

**Comment by Dilshat** [comment]
How to test:
1. Try to issue start/stop/restart/destroy command for multiple containers, e.g.:
`subutai stop foo bar zzz`
Result: all specified containers must be stopped

**Comment by kurmanbekova6** [comment]
Followed the test case described above^
Result:
Start/stop/restart work appropriately.

![screenshot_13](https://user-images.githubusercontent.com/9501291/51161752-def51500-18bd-11e9-9e94-e699a8032f4e.png)
![screenshot_15](https://user-images.githubusercontent.com/9501291/51161753-def51500-18bd-11e9-9abc-c1245172ebcb.png)
![screenshot_16](https://user-images.githubusercontent.com/9501291/51161754-df8dab80-18bd-11e9-9aa0-5630e5b7be24.png)
command `destroy` seems does not work.
After destroying containers, containers will be load endlessly, they will not be destroyed
![screenshot_18](https://user-images.githubusercontent.com/9501291/51161757-df8dab80-18bd-11e9-88f5-496ad6d904d1.png)
![screenshot_21](https://user-images.githubusercontent.com/9501291/51161980-b883a980-18be-11e9-8283-d05a0a702578.png)
![screenshot_19](https://user-images.githubusercontent.com/9501291/51161758-e0264200-18bd-11e9-8a79-c18836a52af1.png)
Here example of another containers:
![screenshot_22](https://user-images.githubusercontent.com/9501291/51162085-24661200-18bf-11e9-8f8e-91c047827aeb.png)
@Dilshat If you need I can create a new issue about destroying containers.
