### ISSUE TITLE
Template metadata cache prevents template import

### ISSUE THREAD

**Issue by Dilshat** [subutai-io/agent#445]
Agent caches metadata of all downloaded templates to speed up further operations.
Currently we faced issue when CDN supplied a borked template that didn't get installed.
The template's metadata got cached and on subsequent attempts to reimport a fixed template, agent used the cached metadata and tried to pull old borked template by ID.
To solve this issue we can have one of these implemented:
1) Cache metadata only if template installs successfully
2) Subutai destroy must clean metadata even if template is not installed

**Comment by AlinaPenkina** [comment]
Fixed on master.
