### ISSUE TITLE
As a user I was able to create peer without RH

### ISSUE THREAD

**Issue by AlinaPenkina** [subutai-io/agent#485]
As a user I was able to create peer without RH.
I used CC to create this peer.

**Comment by AlinaPenkina** [comment]
[karaflogs2018-04-26 11_38_47.txt](https://github.com/subutai-io/agent/files/1949845/karaflogs2018-04-26.11_38_47.txt)
[karaflogs2018-04-26 11_38_52.txt](https://github.com/subutai-io/agent/files/1949846/karaflogs2018-04-26.11_38_52.txt)

**Comment by Dilshat** [comment]
@AlinaPenkina plz recheck

**Comment by liquuid** [comment]
An user has the exact same problem today, I get a copy of his VM to debug.

**Comment by Dilshat** [comment]
@AlinaPenkina @liquuid we need to test this on new prod peers
