### ISSUE TITLE
nginx starts before dnsmasq, makes it fail to start

### ISSUE THREAD

**Issue by happyaron** [subutai-io/agent#514]
On vagrant box testing, we discovered that nginx sometimes fails to start because it starts before dnsmasq, which is required to resolve domain name for nginx. We need to create a dependency for them to make sure nginx is brought up after dnsmasq. A quick solution would be creating a new dumb systemd service file, make it `Requires=dnsmasq.service` and `Before=nginx.service` so that it get injected between them and enforces the dependency.

```
May 02 06:06:02 subutai systemd[1]: Starting A high performance web server and a reverse proxy server...
May 02 06:06:03 subutai nginx[8023]: nginx: [emerg] host not found in upstream "security.ubuntu.com" in /etc/nginx/nginx.conf:67
May 02 06:06:03 subutai systemd[1]: nginx.service: Control process exited, code=exited status=1
May 02 06:06:03 subutai systemd[1]: Failed to start A high performance web server and a reverse proxy server.
May 02 06:06:03 subutai systemd[1]: nginx.service: Unit entered failed state.
May 02 06:06:03 subutai systemd[1]: nginx.service: Failed with result 'exit-code'.
```

**Comment by Dilshat** [comment]
@happyaron @lbthomsen is this issue fixed?

**Comment by happyaron** [comment]
This is not fixed yet, I'll try to work it around in subutai-nginx then.

**Comment by happyaron** [comment]
Fixed in subutai-nginx_0.1+201805191_all.de
