### ISSUE TITLE
 Resource Host Discovery Requirements

### ISSUE THREAD

**Issue by akarasulu** [subutai-io/agent#53]
https://github.com/subutai-io/agent/wiki/Resource-Host-Discovery-Requirements

**Comment by soffokl** [comment]
> The availability announcement MUST contain the unique cryptographic identity (PGP fingerprint) of the resource host. 

In current implementation discovery and connection processes absolutely different. Sending identity is not a problem of discovery. It should be in connection request. 

@akarasulu If you want to mess two things together and make single process for that, you should know that it will take much more time. 

> I.e. Cheap bit shifts, with powers of 2, can be used to raise the period from an initial 8 seconds until the it reaches an upper limit of 4096 seconds.

Wait 1 hour to connect RH is too much. User will think that something broken. Discovery sends single packet only. There is no any overload of network even if we have hundreds of RH. I think that period should never be more then 30 seconds. 

>  There MAY be more than one peer on the LAN. Once bound to a peer, a resource host MUST not allow a second join operation to proceed.

RH is not controlling connection to the peer. Since connection request sent, just SS may reject it or accept. 

> Peers should respond with a lightweight unicast UDP message to the announcing resource host. The unique cryptographic identity (PGP fingerprint) of the peer (not its resource host) should be sent with the response. 

What will we do with peer identity of the peer on RH?

> Existing Discovery Protocols

SSDP, SLP, HTTPU, UPnP. Is there any benefit of using it, except "just in case"?

**Comment by akarasulu** [comment]
> In current implementation discovery and connection processes absolutely different. 

I agree, but we are not mixing the two. We are just including an additional parameter for the identity to prevent an unnecessary response by a peer that already rejected the request. 

> Sending identity is not a problem of discovery. It should be in connection request.

The fingerprint is simply there for peers to filter out previously rejected RHs. Otherwise we will have a RH constantly requesting a join to the peer. The peer admin will have to reject again.  

> @akarasulu If you want to mess two things together and make single process for that, you should know that it will take much more time.

One extra parameter for filtration is going to **mess two things together**? And it's going to take much more time? Are you sure this is not an exaggeration?

**Comment by soffokl** [comment]
Add fingerprint to the discovery package is not a problem. Problem that we do not have process for handling it. Agent handling discovery requests. 

We already have fingerprint in join request, no need to add it to discovery request.

**Comment by akarasulu** [comment]
> Wait 1 hour to connect RH is too much. User will think that something broken. 

OK we can keep it down. You make a good point. I still think we should use some kind of decay and keep it down to minutes. Are you suggesting not even doing a exponential increase in time? Most discovery protocols do stuff like this.

> Discovery sends single packet only. There is no any overload of network even if we have hundreds of RH. I think that period should never be more then 30 seconds.

OK let's do it this way if we can get one more approval for it. This way we do not need a decay at all.

**Comment by akarasulu** [comment]
> RH is not controlling connection to the peer. Since connection request sent, just SS may reject it or accept.

Can you elaborate more?

**Comment by akarasulu** [comment]
> Add fingerprint to the discovery package is not a problem. Problem that we do not have process for handling it. Agent handling discovery requests.

I see now what you're saying now ... also from this comment:

>  Including SS to this process will take more time.

Let's not worry about the time, and focus on doing this the right way. I REALLY appreciate that you want to fix this bug as fast as possible for our users!

Am I correct in summarizing the issue as: The management server **MUST** inform the agent about RH's that have been rejected or abandoned so the agent (in the peer role) can ignore responding to an unbound resource host's availability broadcast? 

A file listing the fingerprints of unbound resource hosts to "**ignore**" should be enough for the agent in the peer role. Perhaps the peer's management server could append the file when a join request is rejected or when a RH is removed from a peer. 

**NOTE** @Dilshat @tjamakeev the peer management server **SHOULD** still track these rejected RHs internally in its database just in case: by ignoring them for discovery it will not see them again. If it needs to it can contact directly from using its database. Or use information in this database to remove ignored candidates from the ignores file of the agent.

IMO we do not want RHs constantly asking over and over again to re-join after being rejected. SS needs to deal with this by updating the ignored RH listing of the agent.

**Comment by akarasulu** [comment]
> What will we do with peer identity of the peer on RH?

I just included this for two reasons. 

1. symmetry between requests and responses 
2. for future use in scenarios requiring new RHs to authorize a specific peer to join. I can new RH's launched saying "You were created for this peer, so use only this peer to send join requests to."

**Comment by soffokl** [comment]
In this case will be much easy to implement UDP discovery server in SS. Actually I think this is a right place for Discovery server. 

> IMO we do not want RHs constantly asking over and over again to re-join after being rejected. SS needs to deal with this by updating the ignored RH listing of the agent.

If RH rejected once it can be allowed later. I think RH should keep trying to connect

**Comment by akarasulu** [comment]
> SSDP, SLP, HTTPU, UPnP. Is there any benefit of using it, except "just in case"?

Yes there is. When we say we use SSDP for example for discovery then it is all documented and not something we invented here. I want to avoid having our own mechanisms for everything. SSDP is trivial enough and close enough to what we want and need. It might involve a tiny bit more attention to deal with the library and the protocol but I think it pays off later.

**Comment by akarasulu** [comment]
> If RH rejected once it can be allowed later. I think RH should keep trying to connect

This case is easiest of all. The management server does nothing: it does NOT add the fingerprint to the ignores list.

**Comment by soffokl** [comment]
> This case is easiest of all. The management server does nothing: it does NOT add the fingerprint to the ignores list.

Where this ignores list located?

**Comment by akarasulu** [comment]
> Where this ignores list located?

On the RH (in peer role with the management container) somewhere next to the agent's configuration file?

**Comment by soffokl** [comment]
> On the RH (in peer role with the management container) somewhere next to the agent's configuration file?

Then unbound RH should keep trying to connect. 

And as I told above I think discovery server should be in SS.

**Comment by akarasulu** [comment]
IMO the discovery mechanism is a low level networking matter that should be handled at the level of the operating system instead of in a java application. I want less and less in the java side to eventually be able to replace it with something less resource intensive.

**Comment by soffokl** [comment]
But since we should anyway use SS for handling rejected hosts it should be in single place.

**Comment by akarasulu** [comment]
> But since we should anyway use SS for handling rejected hosts it should be in single place.

I totally agree with your philosophy but I do not think it applies here all that much. Let me explain my thinking. The agent is intact with this extended configuration for ignored RHs: it's like the hosts.deny lists. The SS management server does what it is supposed to do, "**manage**" this lower level subos configuration based on its own higher level workflow and interactions with users. It's the right boundary.

Later on with golang UI for managing things it can all, including higher level workflow, be co-located.

**Comment by Dilshat** [comment]
Current implementation of SS is simple in this particular case:
Agent sends registration request.
The request on SS side has the following states: 
REQUESTED - request has arrived but not handled by admin yet
APPROVED - admin approved RH to join
REJECTED - admin rejected RH to join, subsequent requests will be ignored until admin removes rejection
If admin removes rejected or approved RH, RH can again send registration request which will become REQUESTED again
