### ISSUE TITLE
Removing container from https vhost is broken.

### ISSUE THREAD

**Issue by p1gmale0n** [subutai-io/agent#54]
if vhost have 1 upstream, deleting upstream does not execute the addition of "dummy" upstream:
https://github.com/subutai-io/agent/blob/master/cli/proxy.go#L170-L172

[proxy.del.upstream.https.txt](https://github.com/subutai-io/agent/files/698533/proxy.del.upstream.https.txt)

**Comment by tzununbekov** [comment]
Fix pushed to dev branch
