### ISSUE TITLE
Add tcp/udp protocols support to `proxy` binding 

### ISSUE THREAD

**Issue by tzununbekov** [subutai-io/agent#55]
Design and implement reverse proxy binding's function to forward not only http, but also tcp and udp traffic

**Comment by tzununbekov** [comment]
Been thinking about this feature and got to the conclusion that we need to have environment entities stored in agent's database. Why? First of all to keep metadata structured and easy manageable. Currently, the only identifier that binds all containers of the same environment with each other is a vlan tag which is stored in very different places in the system. It is already adds limitations, such as "one env - one domain". Second practical necessity - environment cleanup function is an ugly bunch of functions that was added to define if this container is a part of environment and which interface/tunnel/uuid/domain belongs to this container. Adding tcp/udp port mapping will create more metadata that should be somehow bonded with environment entity.
Having all this data structured in agent's database will make code significantly cleaner, increase application performance and provide more flexibility for further development

**Comment by tzununbekov** [comment]
Regarding tcp/udp proxying, I think it should be something like this:

`subutai proxy add <group id> <dst ip>:<dst port> <tcp|udp>`

where the destination IP and port in usual case is a service socket inside the container. As result value command should return RH's external network socket that being forwarded to the destination (external port in this case will be random free port).

**Comment by akarasulu** [comment]
> Regarding tcp/udp proxying, I think it should be something like this:
>
> `subutai proxy add <group id> <dst ip>:<dst port> <tcp|udp>`
>
> where the destination IP and port in usual case is a service socket inside the container. 

Some questions:

1. Can you elaborate on this `<group id>`?
2. The destination IP/port will be used in the NGINX proxy configuration correct? 
3. The NGINX proxy will reside on every RH?
4. Are you presuming ports to the outside might be exposed on every RH in the peer? This might be good. Cloud peers can expose. Problem for edge users but they can expose too.
5. Any value in using the container's name or internal DNS name instead to get an extra layer of indirection? If IP changes occur using the name might insulate us from having to change the configuration each time, but can NGINX resolve these names?  

Trying to get the big picture here.

> As result value command should return RH's external network socket that being forwarded to the destination (external port in this case will be random free port). 

What do you mean by `value command`? 

Thanks!

**Comment by tzununbekov** [comment]
> Can you elaborate on this <group id>?
It should be some unique identifier for each tcp/udp port or http domain forwarded by reverse proxy. Currently, for http, we are using vlan number to bind certain environment with domain name and containers, but it adds limitation of single domain on environment. Actually, I think that we can get rid of this id and use tcp/udp sockets or http domains as identifiers.

> The destination IP/port will be used in the NGINX proxy configuration correct?
Correct

> The NGINX proxy will reside on every RH?
Yes, nginx is a service on every RH

> Are you presuming ports to the outside might be exposed on every RH in the peer? This might be good. Cloud peers can expose. Problem for edge users but they can expose too.
I don't see the necessity to expose ports on every RH in the peer. Currently, for http forwarding, only RH-with-MH accepts incoming requests which are being distributed between containers on different RHs by nginx over p2p connection.    

> Any value in using the container's name or internal DNS name instead to get an extra layer of indirection? If IP changes occur using the name might insulate us from having to change the configuration each time, but can NGINX resolve these names?
Nginx can use both IP addresses and domain names as backend destination, but since our container names and IP addresses are bound by entries in /etc/resolv.conf there are no much reasons to swap IP by names. In future, when we will improve internal DNS service we can easily do it.   

> What do you mean by `value command`?
Probably, there should be a comma: `As result value, command should return RH's external network socket` - means that command should return something like `192.168.0.13:4523` as a result of command execution

**Comment by akarasulu** [comment]
> > Can you elaborate on this \<group id\>?
> It should be some unique identifier for each tcp/udp port or http domain forwarded by reverse proxy. 

> Currently, for http, we are using vlan number to bind certain environment with domain name and containers, but it adds limitation of single domain on environment. Actually, I think that we can get rid of this id and use tcp/udp sockets or http domains as identifiers.

I don't understand why it limits us. Can't we map multiple domains to the same environment even with VLANs? Can you explain where this limitation is coming from?

BTW let's use some common vocabulary: **Environment Segment:** `The part of a virtual network environment and its containers hosted on a peer.`

Also, to keep discussions simple and focused, maybe we can keep these two topics separated:

 - Removing the use of VLANs for environment segment isolation
 - Associating environment segments with domains and proxying traffic to those containers inside 

If we can, let's discuss removing VLANs in another issue: this one is complicated enough. Is it even possible to decouple mappings from the VLAN id and still have the `group id` you need? Maybe we just chose to use the VLAN id for mappings because it was convenient and there: perhaps we avoided creating yet another parameter that way.

> > Any value in using the container's name or internal DNS name instead to get an extra layer of indirection? If IP changes occur using the name might insulate us from having to change the configuration each time, but can NGINX resolve these names?

> Nginx can use both IP addresses and domain names as backend destination, 

Sorry I did not ask correctly. Yes I know NGINX can resolve the names, but only if it can do the DNS lookup to find the container's internal address. The real question is: can we provide the infrastructure needed for NGINX in the RH to resolve the container names. This is the issue. 

> but since our container names and IP addresses are bound by entries in /etc/resolv.conf

I guess you mean the /etc/hosts file?

> there are no much reasons to swap IP by names. In future, when we will improve internal DNS service we can easily do it. 

I was also trying to look ahead and align with the requirements. We're going to be mapping external ports to containers and not to IP's but internally this can be hidden to the user so I guess we can delay this. I still see us hitting a roadblock trying to get NGINX to resolve container names to their IP addresses without being inside the environment. So yeah let's put this off until we have the additional DNS infrastructure in place.

> > What do you mean by `value command`?

> Probably, there should be a comma: `As result value, command should return RH's external network socket` - means that command should return something like `192.168.0.13:4523` as a result of command execution

The IP:PORT exposed is on the peer's LAN correct? How does this port get exposed to the outside Internet?

**Comment by tzununbekov** [comment]
> > Currently, for http, we are using vlan number to bind certain environment with domain name and containers, but it adds limitation of single domain on environment. Actually, I think that we can get rid of this id and use tcp/udp sockets or http domains as identifiers.
>
> I don't understand why it limits us. Can't we map multiple domains to the same environment even with VLANs? Can you explain where this limitation is coming from?

Initially, we were needed to link domains and environments to each other, so our vhost config files named like \<vlan\>.conf, which is why we cannot create more than one vhost on vlan. But this issue is not worth considering, it can be easily changed if needed: "_Actually, I think that we can get rid of this id and use tcp/udp sockets or http domains as identifiers_" 

> The real question is: can we provide the infrastructure needed for NGINX in the RH to resolve the container names. This is the issue.

Yes, we can provide it and looks like issue is already there: https://github.com/subutai-io/subos/issues/629

> I guess you mean the /etc/hosts file?

Right

> I still see us hitting a roadblock trying to get NGINX to resolve container names to their IP addresses without being inside the environment

If we have dnsmasq with environment container names on RH, then Nginx will be able to resolve it

**Comment by akarasulu** [comment]
> > > Currently, for http, we are using vlan number to bind certain environment with domain name and containers, but it adds limitation of single domain on environment. Actually, I think that we can get rid of this id and use tcp/udp sockets or http domains as identifiers.
> >
> > I don't understand why it limits us. Can't we map multiple domains to the same environment even with VLANs? Can you explain where this limitation is coming from?

> Initially, we were needed to link domains and environments to each other, so our vhost config files named like \<vlan\>.conf, which is why we cannot create more than one vhost on vlan. 

OK got it now. This is just because of the scheme we used before.

> But this issue is not worth considering, it can be easily changed if needed: "_Actually, I think that we can get rid of this id and use tcp/udp sockets or http domains as identifiers_" 

Your comments now make total sense: you're going to use the port for `$tcp_udp_port.conf` instead and the `$domain.conf` for HTTP. Phhheeeww finally I understand :dango: 

> > The real question is: can we provide the infrastructure needed for NGINX in the RH to resolve the container names. This is the issue.

> Yes, we can provide it and looks like issue is already there: https://github.com/subutai-io/subos/issues/629

This is music to my ears!!

> > I still see us hitting a roadblock trying to get NGINX to resolve container names to their IP addresses without being inside the environment

> If we have dnsmasq with environment container names on RH, then Nginx will be able to resolve it.

Yeah I was thinking the same. BTW recently while looking at Consul it seems it supports DNS too. Consul might also help us manage environment meta data. Again this is an idea, not me pushing to use Consul: it might not be what we're looking for at all. 

> > The IP:PORT exposed is on the peer's LAN correct? How does this port get exposed to the outside Internet?

> LAN or any local interface, including p2p. 

Hmm do you have some tricks in mind with p2p. 

> Exposing ports to the outside Internet is a complex task which includes not only local peer commands execution, but also Helper node participation. 

Sure in case of NAT'ing but what about exposing the port via the peer if the peer can or has already exposed ports?

> We cannot make agent's CLI execute commands on Helper nodes, so ports exposing to the outside Internet will consists of two steps:
1. Peer's ports forwarding to the p2p tunnel
2. Helper's ports forwarding to the same p2p tunnel
>
> First step will return \<ip\>:\<port\> socket which should be exposed in the second step

Man a diagram would be nice if you could. We can still reuse it in the documentation too. Would help us a lot.

**Comment by akarasulu** [comment]
I know cloud peer resource hosts will have an external IP. Don't you think cloud users will want to expose RH ports for access instead of always having it route through the peer RH? I know we brushed this off but I feel like this might be a valid use case. Can we talk about this tomorrow too?

**Comment by tzununbekov** [comment]
`subutai map <protocol> -i|--internal <socket> -e|--external [RH port] -d|--domain [domain name] [-r|--remove]`

*note: partially, new binding overlaps with `subutai proxy` command, but in sake of compatibility we should keep both of them for a while*

**protocol** - specifies required protocol for mapping and might be http, tcp or udp. 
**-i|--internal** - peer's internal socket that should be exposed. 
**-e|--external** - optional parameter which shows desired RH port where internal socket should be mapped. If more than one container's sockets mapped to one RH port, those containers considered as a cluster.
**-d|--domain** - should be only specified for http protocol mapping
**-r|--remove** - optional flags shows that specified mapping should be removed. If not set, "add" operation is assumed

As a result, exit code 0 will be returned if command succeeded, otherwise exit code 1. When desired RH port is not specified, random port value is also returned from CLI.  

For now, we'll use default values for such things as balancing policy and ssl configuration. We'll get back to additional parameters and configuration when common functionality will be implemented. 

Since new binding has pretty wide functionality and it will be added "from the scratch", its format might be changed during implementation according to the technical restrictions and possible pitfalls. Any changes in command format will be additionally discussed with all affected teams.   

___

Examples: 
- map container's 172.16.31.3 port 3306 to the random port on RH
```
subutai map tcp 172.16.31.3:3306
46558
```
- add 172.16.31.4:3306 to the same group
``` 
subutai map tcp 172.16.31.4:3306 46558
```
- remove container 172.16.31.3 from mapping
``` 
subutai map tcp 172.16.31.3:3306 46558 -r
```
___

- map 172.16.25.12:80 to RH's 8080 with domain name example.com
```
subutai map http 172.16.25.12:80 8080 example.com
```
- add container to existing example.com domain
```
subutai map http 172.16.25.13:80 8080 example.com
```
 
___

Described specification creates port mapping on local resource host. To expose mapping from the NAT'd peer to the outside Web, Hub should initiate p2p tunnel between helper node and NAT'd host and create two local mappings: first one to forward traffic from helper node to RH and second - from RH to container.

**Comment by asanaliev** [comment]
This port mapping looks good for me.

I would also recommend adding a feature to show existing mappings. It might be when running `subutai map` without any options.

> To expose mapping from the NAT'd peer to the outside Web, Hub should initiate p2p tunnel between helper node and NAT'd host and create two local mappings. 

First, I like this idea of separting the port mappings: between a container and RH, RH and a help node. It seems simpler and flexible than trying encapsulate all actions in one shot.

But I am not sure should we use the p2p tunnel for these mappings. I thought p2p had a different purpose.

**Comment by tzununbekov** [comment]
> But I am not sure should we use the p2p tunnel for these mappings. I thought p2p had a different purpose.

Why? If not p2p then what do you suggest?

>  A helper node must expose a given port also, not a random one only

Helper node has limited amount of network ports and single port, if it is not http(s) protocol, cannot be shared between different mappings, so there is a logical technical limitations for this option.

**Comment by asanaliev** [comment]
> Why? If not p2p then what do you suggest?

P2P was created to connect nodes when none of them is directly accessible. That is why it needs control peers to proxy traffic. In our case, a helper node is always accessible. Using p2p would be redundant here. 

There should be some simpler implementations to manage tunnels.

**Comment by tzununbekov** [comment]
> P2P was created to connect nodes when none of them is directly accessible

huh? Looks like we have misunderstanding in general things and it makes me disagree with you.

I'm open to "some simpler implementations" discussion

**Comment by Dilshat** [comment]
P2P should be used as universal means of transport where possible, here I agree with @tzununbekov.
I think, we need to simplify overall scheme and use one consistent approach everywhere without growing number of different types of "setups". However we should make sure that p2p is smart enough to step back and make it transparent for the parties to communicate without additional overhead when it is possible, in cases where proxying is redundant (no doubt it already does this). Higher levels like SS and Hub (and even subos) should not deal with this.
