### ISSUE TITLE
subutai update return value

### ISSUE THREAD

**Issue by lbthomsen** [subutai-io/agent#553]
subutai update return 1 when there is no update available:

`eu2:~# subutai update rh ; echo $?
INFO[2018-05-12 02:56:49] No update is available                       
1
`
In my opinion that is not an error and thus 0 should be returned.

**Comment by lbthomsen** [comment]
`prod-peer-us-2:~# apt-get update ; echo -n -e "\nReturned: $?\n"
Hit:1 http://deb.subutai.io/subutai prod InRelease
Ign:2 http://debian.intergenia.de/debian stretch InRelease                     
Hit:3 http://debian.intergenia.de/debian stretch-backports InRelease
Hit:4 http://debian.intergenia.de/debian stretch-updates InRelease
Hit:5 http://debian.intergenia.de/debian-security stretch/updates InRelease
Hit:6 http://debian.intergenia.de/debian stretch Release
Reading package lists... Done

Returned: 0
prod-peer-us-2:~# apt-get upgrade ; echo -n -e "\nReturned: $?\n"    
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Calculating upgrade... Done
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.

Returned: 0
prod-peer-us-2:~# apt upgrade ; echo -n -e "\nReturned: $?\n"
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Calculating upgrade... Done
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.

Returned: 0
prod-peer-us-2:~# subutai update rh ; echo -n -e "\nReturned: $?\n"
INFO[2018-05-11 21:26:22] No update is available                       

Returned: 1
prod-peer-us-2:~# subutai -d update rh ; echo -n -e "\nReturned: $?\n"
DEBU[2018-05-11 21:28:35] Init lock rh.update                          
DEBU[2018-05-11 21:28:35] Locking file rh.update                       
DEBU[2018-05-11 21:28:37] Updating apt index                           
DEBU[2018-05-11 21:28:37] Checking for available update                
INFO[2018-05-11 21:28:37] No update is available                       

Returned: 1
`

**Comment by Dilshat** [comment]
Requires changes on Console side
