### ISSUE TITLE
Add two resource hosts to same peer

### ISSUE THREAD

**Issue by marcoarthur** [subutai-io/agent#582]
User follow these steps:

1.  Create 2 peerOS using control Center.
2.  Deleted management from one PeerOS (peerOS are in the same network I suppose) that make it unbound state.

Expected behavior was:  unbound RH to communicate with management and to be added as resource host automatically.

**Comment by Dilshat** [comment]
Peer does not autoapprove second RHs
You need to visit Resource Hosts page, find the RH and approve it.
If you dont see second RH there, please use this instruction to connect it to peer:
https://github.com/subutai-io/agent/wiki/How-to-add-second-RH-to-peer
