### ISSUE TITLE
Migrate from gnupg1 to gnupg2

### ISSUE THREAD

**Issue by happyaron** [subutai-io/agent#593]
We are still using gnupg1 in agent for processing PGP keys, it is good to migrate to gnupg2 since gnupg1 is a bit deprecated-ish and the dependency handling on debian package can be awkward.

**Comment by happyaron** [comment]
Background of why gnupg1 is unclear, but could be that it is available in snap environment. If we change the gnupg implementation being used we need to test thoroughly with Console thanks to @Dilshat

**Comment by Dilshat** [comment]
@happyaron be aware while handling this issue you will need to change agent code.
Just swapping gpg is not enough

**Comment by akarasulu** [comment]
This is a really important issue for us to do. Please prioritize it.

**Comment by happyaron** [comment]
Having a `gpg2` branch now, but as @Dilshat reviews it still requires some more changes to get it work and compatible to Console and Bazaar, but a new question pops up here:

1. Upstream says it will not abandon gpg1 anytime soon, even they are promoting gpg1 loudly and I discovered a tiny paragraph about gpg1:
```GnuPG 1.4 is the _old_, single binary version which still support the unsafe PGP-2 keys. This branch has no dependencies on the above listed libraries or the Pinentry. However, it lacks many modern features and will receive only important updates. ```
This means gpg1 is not going to disappear and it will fit for embed and many scenario that space and speed is more concerned than fancy features.

2. After a deeper look into the comparison gpg2 provides the ability of using  S/MIME which gpg1 does not support. Otherwise the differences are more about internals, gpg2 builds upon a list of libraries, and gpg1 is more self-contained. Also gpg2 requires the usage of gpg-agent which gpg1 does not. There aren't real differences on supported algorithms.

So considering gpg1 is still actively maintained, and the main usage in agent is about PGP/MIME signing and encryption, I'm personally hesitate about shall we continue down this way, or rather hold back and keep it as-is?

**Comment by happyaron** [comment]
Since ECDSA is wanted and gpg1 does not support it in pubkey, lets continue the migration.

```$ gpg1 --version                                                                                                                                ~
gpg (GnuPG) 1.4.21
Copyright (C) 2015 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Home: ~/.gnupg
Supported algorithms:
Pubkey: RSA, RSA-E, RSA-S, ELG-E, DSA
Cipher: IDEA, 3DES, CAST5, BLOWFISH, AES, AES192, AES256, TWOFISH,
        CAMELLIA128, CAMELLIA192, CAMELLIA256
Hash: MD5, SHA1, RIPEMD160, SHA256, SHA384, SHA512, SHA224
Compression: Uncompressed, ZIP, ZLIB, BZIP2```

```$ gpg2 --version                                                                                                                                ~
gpg (GnuPG) 2.1.18
libgcrypt 1.7.6-beta
Copyright (C) 2017 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Home: /home/aron/.gnupg
Supported algorithms:
Pubkey: RSA, ELG, DSA, ECDH, ECDSA, EDDSA
Cipher: IDEA, 3DES, CAST5, BLOWFISH, AES, AES192, AES256, TWOFISH,
        CAMELLIA128, CAMELLIA192, CAMELLIA256
Hash: SHA1, RIPEMD160, SHA256, SHA384, SHA512, SHA224
Compression: Uncompressed, ZIP, ZLIB, BZIP2```

**Comment by Dilshat** [comment]
closed for now
