### ISSUE TITLE
zfs command hangs

### ISSUE THREAD

**Issue by Dilshat** [subutai-io/agent#598]
Sometimes zfs commands that create or destroy datasets hang which in turn makes agent hang too
```
root      4781  0.0  0.0  35244  3432 ?        S    May22   0:00 zfs destroy -r subutai/fs/wp-39D-2gl-3-4
root      4785  0.0  0.0  23624  1240 ?        D    May22   0:00 /bin/umount -t zfs /var/lib/lxc/wp-39D-2gl-3-4/opt
root      9954  0.0  0.0  35244  3380 ?        D    05:13   0:00 zfs create subutai/fs/Container-1-ugZ-oq1-3-4
root     18635  0.0  0.0  35244  3460 ?        D    May22   0:00 zfs create subutai/fs/Container-1-y0d-c7a-6-3
root     18665  0.0  0.0  35244  3384 ?        D    May22   0:00 zfs create subutai/fs/Container-1-pdc-g2j-3-3
root     32215  0.0  0.0  35244  3344 ?        S    May22   0:00 zfs destroy -r subutai/fs/ansible-server-152-mgL-yoc-3-3
root     32219  0.0  0.0  23624  1284 ?        D    May22   0:00 /bin/umount -t zfs /var/lib/lxc/ansible-server-152-mgL-yoc-3-3/rootfs
```

**Comment by Dilshat** [comment]
https://github.com/zfsonlinux/zfs/issues/3104

**Comment by Dilshat** [comment]
http://zfs-discuss.opensolaris.narkive.com/uubAR7hT/zfs-destroy-hangs-machine-if-snapshot-exists-workaround-found

**Comment by Dilshat** [comment]
http://list.zfsonlinux.org/pipermail/zfs-discuss/2016-March/024959.html

**Comment by Dilshat** [comment]
https://forums.freebsd.org/threads/zfs-hangs-while-removing-large-file.51054/

**Comment by Dilshat** [comment]
can not use **timeout** command because `kill -9` does not work, only reboot helps

**Comment by Dilshat** [comment]
So you suggest to destroy each child dataset and then parent dataset individually?

**Comment by happyaron** [comment]
Yes this will mitigate the problem to a low occurring rate. Also if we can schedule the destroy operation in a serial manner then it should go away, according to my tests.

**Comment by AlinaPenkina** [comment]
Fixed.
