### ISSUE TITLE
Questions regarding agent vs. CLI based actions

### ISSUE THREAD

**Issue by akarasulu** [subutai-io/agent#60]
## Current Setup

 - The agent exposes a REST API for remote operations on a RH
 - The agent requires authenticated and authorized clients to use its REST API
 - The SS management console issues commands through the agent's REST API
 - For Subutai container and environment management operations the agent forks the subutai CLI program
 - Administrators logged into the RH on a TTY can directly invoke subutai CLI commands

## Questions

1. How much of an effort would it take to create a library for container and management commands while still having a Subutai CLI Wrapper?
2. How much of an effort would it take to have the agent use the Subutai library instead of forking the Subutai CLI Wrapper?

## Reasoning

We have two different pathways for environment modifications:

 - **Managed**: SS Management => Agent REST API => Subutai Commands
 - **Unmanaged**: Administrator on RH => Subutai Commands

This is creating some consistency and security problems:

1. Unmanaged activities are not monitored or logged properly and they need to be.
2. SS Management needs to be aware of modifications made through unmanaged channels to maintain a consistent model of environment state.

**Comment by soffokl** [comment]
> The agent exposes a REST API for remote operations on a RH

Incorrect. 

> The agent requires authenticated and authorized clients to use its REST API

Incorrect.

> The SS management console issues commands through the agent's REST API

Incorrect.

Subutai Agent does not provide REST API for command execution. SS provides REST API, and Agent uses this to get queue of command that should be executed. 

> For Subutai container and environment management operations the agent forks the subutai CLI program

For container operation Agent uses liblxc with attach mechanism for execution commands. 

For RH operations Agent execute fork commands. 

Execution commands as fork process add stability to the system. No any crash can stop Agent.


> Administrators logged into the RH on a TTY can directly invoke subutai CLI commands

User on RH may use any commands including subutai CLI. That mean we cannot catch any changes in system to notify SS about it. We can just rescan it with some period

**Comment by akarasulu** [comment]
OK got it. We have a pull model. This is a remnant of when we used to have MQTT. Right not much we can do here. Thanks for the update.
