### ISSUE TITLE
Cannot destroy container,  filesystem has dependent clones

### ISSUE THREAD

**Issue by liquuid** [subutai-io/agent#603]
I faced the following error while destroy template:

```
Removing template, Removing zfs dataset/snapshot nginx:subutai:0.4.1 exit status 1: cannot destroy 'subutai/fs/nginx:subutai:0.4.1': filesystem has dependent clones
use '-R' to destroy the following datasets:
subutai/fs/ngx/rootfs
subutai/fs/ng/rootfs
subutai/fs/Container1-aip-1-2/rootfs
```

**Comment by Dilshat** [comment]
@liquuid seems  you tried to destroy template **nginx** that either had child containers or child templates in the peer

**Comment by liquuid** [comment]
Yes, do you think is a good idea allow a recursive removing, using a flag on cli command ?

**Comment by Dilshat** [comment]
Template might be used by other users' containers, we can not remove it without removing them.
Better remove children explicitly so we know what we are doing

**Comment by liquuid** [comment]
hum... I think, I was confused by `subutai list` from 7.0.2 , it did not show some of childs... I redo the tests using 7.0.3 and can able to see all childs. Need do some more tests on this subject.
