### ISSUE TITLE
SSDP server not responding to client multicast request

### ISSUE THREAD

**Issue by jadilet** [subutai-io/agent#633]
ControlCenter multicast request like:

![screenshot from 2018-06-08 11-22-05](https://user-images.githubusercontent.com/6593519/41140272-3eafe91a-6b0e-11e8-809a-cb3e431fd26c.png)

**Comment by Dilshat** [comment]
@jadilet see here for details on how server works https://github.com/diversario/node-ssdp

**Comment by soffokl** [comment]
@jadilet SSDP is not an HTTP request, you need to send UDP packets specified in the [protocol](https://ru.wikipedia.org/wiki/Simple_Service_Discovery_Protocol) to get an answer. 

@Dilshat 🙌

**Comment by crioto** [comment]
SSDP is based on HTTPU, which is based on HTTP, which is sent over UDP. @soffokl UDP and HTTP are on different network layers

**Comment by soffokl** [comment]
@crioto oh, sorry for the disturbing. 🌚

**Comment by AlinaPenkina** [comment]
Fixed.
