### ISSUE TITLE
Exit with error when a container with name longer than 63 symbols is cloned

### ISSUE THREAD

**Issue by Dilshat** [subutai-io/agent#703]
When an attempt to clone a container with name longer than 64 symbols is made, agent must exit with error

**Comment by Dilshat** [comment]
The labels must follow the rules for ARPANET host names.  They must
    start with a letter, end with a letter or digit, and have as interior
    characters only letters, digits, and hyphen.  There are also some
    restrictions on the length.  Labels must be 63 characters or less.

**Comment by AlinaPenkina** [comment]
Fixed in master.
