### ISSUE TITLE
Stale MH IP on secondary RH

### ISSUE THREAD

**Issue by Dilshat** [subutai-io/agent#717]
When MH changes its IP, secondary RH that was connected to MH, looses connection because does not renew IP.

**Comment by Dilshat** [comment]
The problem was that another RH acquired old MH IP and responded to requests from agent

**Comment by Dilshat** [comment]
How to test:

Setup peer with second RH
on MH (RH with MC) renew ip , see https://www.cyberciti.biz/faq/howto-linux-renew-dhcp-client-ip-address/

Second RH must connect after some time successfully to RH

**Comment by etursunbaev** [comment]
Build 2 peers with Vagrant+VirtualBox:
Peer1 192.168.66.84 MH
Peer2 192.168.66.86 second RH

Peer1 discovered Peer2
![screenshot from 2018-08-29 17-39-25](https://user-images.githubusercontent.com/33412152/44785386-8513dd00-abb2-11e8-9711-7b93b486c169.png)

It took ip addresses from office router, so changed peer1 ip address in gateway manual to address 192.168.66.145
After 2-3 mins it discovered again second rh peer2
![145](https://user-images.githubusercontent.com/33412152/44785898-48e17c00-abb4-11e8-9b55-1c308b0747c9.png)
Third attempt
Changed MH address to 192.168.66.99
And in 2-3 mins it discovered again
![99](https://user-images.githubusercontent.com/33412152/44786531-4122d700-abb6-11e8-8e46-d7f18f7825dd.png)


So it works!
