### ISSUE TITLE
Use only one archiving library

### ISSUE THREAD

**Issue by happyaron** [subutai-io/agent#719]
Agent uses two archiving libraries at the moment:
```
lib/fs/file.go
6:      "github.com/jhoonb/archivex"
```
```
cli/import.go
10:     "code.cloudfoundry.org/archiver/extractor"
```

If I understand correctly the first one is used to create tar files, while the latter is to extract. Please choose one to use for both purpose, thanks!

**Comment by AlinaPenkina** [comment]
This is code based changes.
