### ISSUE TITLE
Introduce cop service for service healthcheck

### ISSUE THREAD

**Issue by happyaron** [subutai-io/agent#723]
A dedicated healthcheck service called `subutai-cop` is involved, which will not only check status of known services regularly, but also be triggered when a service unit are put into `failed` state by systemd. This can improve error handling in several headache cases:

1. Service dead when all restart attempt from systemd are failed
2. Dead service is not restored at package update time
3. Service dying not being discovered for a long time

What to do

- All known services are checked regularly (every ~1h) for status: `active`, `failed`, `disabled`
- When an undesired state is discovered, either try to recover (failed), or inform the user (disabled)
- When systemd decides to put a service into `failed` state, notify this service to rescue.

**Comment by Dilshat** [comment]
Similar functionality already provided by systemd and unit files.
Some of functionality is superseded by https://github.com/subutai-io/guardian
