### ISSUE TITLE
Subutai prune command fails on child templates

### ISSUE THREAD

**Issue by Dilshat** [subutai-io/agent#754]
subutai prune commands must destroy templates that dont have child templates or containers but it fails with child templates present.

How to reproduce: 
On a peer without template or containers, import debian-stretch and generic-ansible
Then run `subutai prune`, it should destroy both templates

**Comment by AlinaPenkina** [comment]
Test case: 
1. Brought peer up.
2. Imported debian-stretch and generic ansible.
3. Destroyed via subutai prune.

Fixed in Master

**Comment by Shahrizada** [comment]
<img width="842" alt="screen shot 2018-08-29 at 11 24 09 am" src="https://user-images.githubusercontent.com/31571523/44767306-326cfd80-ab7f-11e8-8858-07b2c19436ca.png">
<img width="1069" alt="screen shot 2018-08-29 at 11 31 05 am" src="https://user-images.githubusercontent.com/31571523/44767308-326cfd80-ab7f-11e8-9ea2-e6b32d0cf9a3.png">
