### ISSUE TITLE
Port mapping removal works wrong

### ISSUE THREAD

**Issue by samsonbek** [subutai-io/agent#798]
When you delete port mapping by specifying all parameters (external port, internal port, ip), if no port mapping found which matches given query, it deletes next port mapping whose external port matches given external port, but IP is different. This happens only if there is only one port mapping left by given external port.

In following output I executed command to remove `tcp -e 2222 -i 172.17.12.4:22`,
but it removed same port mapping of container with IP `172.17.12.3`
(_for simplicity reserved port mappings are not shown_)

```
root@dop2:~# subutai -v
8.0.0+201809130327490
root@dop2:~# 
root@dop2:~# subutai list info
NAME			STATE	IP		Interface
----			-----	--		---------
Container-1-kud-bcr-1-3	RUNNING	172.17.12.3	eth0
Container-2-gHU-zcj-1-4	RUNNING	172.17.12.4	eth0
management		RUNNING	10.10.10.1	eth0
root@dop2:~# 
root@dop2:~# subutai map list
root@dop2:~# 
root@dop2:~# subutai map add -p tcp -e 2222 -i 172.17.12.3:22
INFO[2018-09-18 14:35:44] 192.168.88.226:2222                          
root@dop2:~# 
root@dop2:~# subutai map add -p tcp -e 2222 -i 172.17.12.4:22
INFO[2018-09-18 14:35:50] 192.168.88.226:2222                          
root@dop2:~# 
root@dop2:~# subutai map list
tcp	0.0.0.0:2222	172.17.12.3:22
tcp	0.0.0.0:2222	172.17.12.4:22
root@dop2:~# 
root@dop2:~# subutai map rm -p tcp -e 2222 -i 172.17.12.4:22
root@dop2:~# 
root@dop2:~# subutai map list
tcp	0.0.0.0:2222	172.17.12.3:22
root@dop2:~# 
root@dop2:~# subutai map rm -p tcp -e 2222 -i 172.17.12.4:22
root@dop2:~# 
root@dop2:~# subutai map list
root@dop2:~# 
```

If there is more than one port mapping by given external port, then it works correct (doesn't remove port mappings of other IP's by mistake):
```
root@dop2:~# subutai map list
tcp	0.0.0.0:2222	172.17.12.3:22
tcp	0.0.0.0:2222	172.17.12.4:22
root@dop2:~# 
root@dop2:~# subutai map rm -p tcp -e 2222 -i 172.17.12.5:22
root@dop2:~# 
root@dop2:~# subutai map list
tcp	0.0.0.0:2222	172.17.12.3:22
tcp	0.0.0.0:2222	172.17.12.4:22
```

**Comment by Dilshat** [comment]
How to test:
On RH run 
`subutai map add -p tcp -e 2222 -i 172.17.12.3:22`
then run
`subutai map rm -p tcp -e 2222 -i 172.17.12.4:22`
this command should not delete prev mapping because IP is different
then run 
`subutai map rm -p tcp -e 2222 -i 172.17.12.3:22`
this time mapping should be deleted

**Comment by kurmanbekova6** [comment]
Fixed in Master
![screenshot_11](https://user-images.githubusercontent.com/9501291/45820516-be022600-bd08-11e8-96a0-a9e747cd08b5.png)
