### ISSUE TITLE
add human friendly output for "subutai tunnel add localhost" command

### ISSUE THREAD

**Issue by Dilshat** [subutai-io/agent#810]
we need to have output in form `ssh root@{ip} -p {port}`
for this we can use an optional switch **-h**

**Comment by Dilshat** [comment]
`subutai tunnel add ... --ssh` was added

**Comment by Dilshat** [comment]
How to test:

Add ssh tunnel using : `subutai tunnel add localhost -s`

Result: output should be in form `ssh root@{ip} -p {port}`

**Comment by kurmanbekova6** [comment]
![screenshot_16](https://user-images.githubusercontent.com/9501291/47630255-ed0e8180-db69-11e8-8ece-bac031c08587.png)
Tested in master

**Comment by etursunbaev** [comment]
btw this is awesome change :+1:
