### ISSUE TITLE
restore-forwarding script uses wrong switch

### ISSUE THREAD

**Issue by Dilshat** [subutai-io/agent#820]
restore-forwarding script uses wrong switch `-i` to obtain list of containers

**Comment by Dilshat** [comment]
How to test:

Create BZR env on a peer, then restart RH with containers, and try to ssh into a container via ez-ssh

Result: ez-ssh should work

**Comment by kurmanbekova6** [comment]
![screenshot from 2018-10-30 13-06-39](https://user-images.githubusercontent.com/9501291/47701693-e1dc5400-dc44-11e8-9d8b-e6d52657028f.png)
Fixed in master
