### ISSUE TITLE
Optimize discovery when mh-ip/fingerprint are explicitly set

### ISSUE THREAD

**Issue by dilshat** [subutai-io/agent#823]
When mh-ip and/or fingerprint are explicitly set, agent still needs ssdp to connect to peer.
We need to have agent attempt to directly connect to it

**Comment by Dilshat** [comment]
How to test:
1) On peer stop agent `service subutai stop`
2) Connect secondary RH to peer via agent config, edit `/etc/subutai/agent.conf` and set parameter **Host** to peer IP , restart agent `service subutai restart`

Result: On Console `Resource hosts` section, secondary RH request must appear

**Comment by kurmanbekova6** [comment]
Tested in master
![screenshot_2](https://user-images.githubusercontent.com/9501291/48842783-07431600-ed4a-11e8-91a2-790adae89038.png)
