### ISSUE TITLE
Enable single letter container names

### ISSUE THREAD

**Issue by dilshat** [subutai-io/agent#837]
Wrong regex prevents single letter container names in clone command

**Comment by Dilshat** [comment]
How to test:
1) Create container using CLI `subutai clone debian-stretch:subutai:0.4.6 m`
Result: container named `m` must be successffully cloned

**Comment by etursunbaev** [comment]
@Dilshat this template afaik is not on master yet. But I can upload to master too.

**Comment by Dilshat** [comment]
@etursunbaev concrete template does not matter, it was just an example. QA can use any template for testing

**Comment by kurmanbekova6** [comment]
Tested in master
![screenshot_8](https://user-images.githubusercontent.com/9501291/48823300-2a070780-ed15-11e8-997a-db31ec2fb14f.png)
