### ISSUE TITLE
Fix container fingerprint determination

### ISSUE THREAD

**Issue by dilshat** [subutai-io/agent#846]
Agent returns wrong container id (fingerprint), sometimes it returns RH id

**Comment by Dilshat** [comment]
Steps to test:
1) Create several containers manually: ```subutai clone a ; subutai clone b ; subutai clone c```
2) Check their ids ```subutai info id a; subutai info id b; subutai info id c```
3) Check RH id ```subutai info id```
Result: all ids must be different

**Comment by Almansherov** [comment]
All ids are different: 

![image](https://user-images.githubusercontent.com/32430693/48884350-c0a4f880-ede9-11e8-8cee-2a3685a2ddb6.png)
