### ISSUE TITLE
Support for peer os 2718

### ISSUE THREAD

**Issue by Dilshat** [subutai-io/agent#849]
Support for https://github.com/subutai-io/peer-os/issues/2718

**Comment by Dilshat** [comment]
How to test:
1. Create container via subutai cli: `subutai clone ...`. Go to console, in Environments->Containers section the container should appear very fast
2. Start/stop the container. Console should display the actual container status very fast
3. Destroy the container. Console should remove the container from UI very fast

**Comment by kurmanbekova6** [comment]
Followed the steps described above:
Result: Container appeared immediately. Start/stop works. Container's state on bazaar changing as well.
Tested in master
