### ISSUE TITLE
Use lxc.start.auto to start containers

### ISSUE THREAD

**Issue by Dilshat** [subutai-io/agent#869]
Currently agent attempts to start containers that are supposed to be running itself.
It attempts to start them 5 times. Sometimes after peer reboot, these are not enough.
So instead of increasing number of attempts, we should first try to use built-in lxc option `lxc.start.auto` for this.
https://coderwall.com/p/ysog_q/lxc-autostart-container-at-boot-choose-order-and-delay

**Comment by Dilshat** [comment]
How to test:
1. Create several containers
2. Reboot peer
Result: all container that had RUNNING state must be RUNNING after reboot
Repeat the same for `vagrant reload`

**Comment by kurmanbekova6** [comment]
Followed the steps described above: 
![screenshot_4](https://user-images.githubusercontent.com/9501291/49718088-e6b20180-fc0d-11e8-910c-8ca0da999a3a.png)
Tested in master
