### ISSUE TITLE
Fix subutai.restore-forwarding service to respect destroyed containers

### ISSUE THREAD

**Issue by Dilshat** [subutai-io/agent#904]
When a container is destroyed, its iptable rule is left until peer is rebooted.
We need to handle this in the service itself

**Comment by Dilshat** [comment]
How to test:
1. Create container
2. Find its iptable rule using `iptables -t nat -L | grep {container-ip}`
3. Destroy the container
Result: within 30 sec the iptable rule should disapper

**Comment by kurmanbekova6** [comment]
![screenshot_2](https://user-images.githubusercontent.com/9501291/49714940-ae0d2a80-fc03-11e8-9983-408614860f90.png)
![screenshot_3](https://user-images.githubusercontent.com/9501291/49714944-afd6ee00-fc03-11e8-955e-d292830ec1ed.png)
Tested in master
