### ISSUE TITLE
Fix "Command timed out" right after container is cloned

### ISSUE THREAD

**Issue by Dilshat** [subutai-io/agent#909]
When a container is just cloned, and immediate command is executed on it (by Console) the command times out.

**Comment by Dilshat** [comment]
How to test:
Create environment from at least 4 containers of generic-ansible templates
Result: environment must be successfully created

**Comment by etursunbaev** [comment]
I think better to test with BP
With manual env creation it worked w/o issues.

**Comment by kurmanbekova6** [comment]
Created environments with generic-ansible template.
Tested with blueprints as well.
![screenshot_9](https://user-images.githubusercontent.com/9501291/49985218-1455be00-ff20-11e8-8f64-8b79fe0a7cd2.png)
Tested in master
