### ISSUE TITLE
Can't ping host machine from inside Subutai container on VM peer

### ISSUE THREAD

**Issue by samsonbek** [subutai-io/agent#928]
How to reproduce:
1. create Virtual Machine peer (in my case it is VirtualBox VM)
2. create Subutai container on that peer
3. attach to container or ssh into it and ping LAN IP of host machine
Result: ping doesn't work, target unreachable. But internet is working inside container.

Setup scheme:
Host machine <-------> guest VM peer <--------> Subutai container.

**Comment by lbthomsen** [comment]
I commented on that one a couple of times before.  It is obviously not a subutai issue - it's an issue between the host and the vm.  Most likely a routing problem.  Host know about the vm but have a default gateway to the internet.  vm know about the container but have a default gw to the host.  container can send packages to vm and host but host when replying will shoot those packages out the default gateway and they won't reach container.
