### ISSUE TITLE
Fix template creation [Master]

### ISSUE THREAD

**Issue by kurmanbekova6** [subutai-io/agent#931]
![screenshot_3](https://user-images.githubusercontent.com/9501291/50945060-3578e280-14bd-11e9-93f7-532dd78787fa.png)

**Comment by Dilshat** [comment]
How to test:
create template

**Comment by kurmanbekova6** [comment]
![screenshot_1](https://user-images.githubusercontent.com/9501291/51159849-68ecb000-18b5-11e9-8062-1c4ed11452b8.png)
![screenshot_2](https://user-images.githubusercontent.com/9501291/51159850-68ecb000-18b5-11e9-83d7-ca290c5d2ebc.png)
Fixed in master.
