### ISSUE TITLE
Fix incomplete LE cert chain

### ISSUE THREAD

**Issue by etursunbaev** [subutai-io/agent#936]
We have a bug on our LE obtaining process
Our obtained LE SSL chain is incomplete

Need to change one line:
``` 
ssl_certificate /var/lib/subutai/letsencrypt/live/example.com/cert.pem;
```
to
```
 ssl_certificate /var/lib/subutai/letsencrypt/live/exmaple.com/fullchain.pem;
```

cert.pem -> fullchain.pem

**Comment by etursunbaev** [comment]
Steps to reproduce:
Create any env with any domain name and HTTPS port mapping
Go to https://www.ssllabs.com/ssltest/index.html and check your domain

The result will be that chain incomplete

**Comment by etursunbaev** [comment]
Tested in dev

Before:
`ssl_certificate /var/lib/subutai/letsencrypt/live/example.com/cert.pem;`
![screenshot from 2019-01-15 15-24-34](https://user-images.githubusercontent.com/33412152/51170877-b24ef680-18d9-11e9-8f93-7cc166805df0.png)

After:
`ssl_certificate /var/lib/subutai/letsencrypt/live/example.com/fullchain.pem;`
![screenshot from 2019-01-15 15-38-25](https://user-images.githubusercontent.com/33412152/51171644-a06e5300-18db-11e9-8b9f-58b5f1c5a3f3.png)

Fixed in dev

**Comment by kurmanbekova6** [comment]
![screenshot_1](https://user-images.githubusercontent.com/9501291/51240628-4ab2ad00-19a6-11e9-9708-68f7bfe75360.png)
![screenshot_3](https://user-images.githubusercontent.com/9501291/51240629-4b4b4380-19a6-11e9-8e7a-41db3517141b.png)
Fixed in master

**Comment by kurmanbekova6** [comment]
![screenshot_1](https://user-images.githubusercontent.com/9501291/51240729-8b122b00-19a6-11e9-8e3d-187ae3928010.png)
![screenshot_3](https://user-images.githubusercontent.com/9501291/51240731-8b122b00-19a6-11e9-8acb-eff2b23fa379.png)
![screenshot_4](https://user-images.githubusercontent.com/9501291/51241600-6028d680-19a8-11e9-8979-8ba144fb01d2.png)
![screenshot_5](https://user-images.githubusercontent.com/9501291/51241768-b9910580-19a8-11e9-8df6-533b6dd4a4f6.png)

The line has not changed.
Tested on updated peers.
Failed in master

**Comment by kurmanbekova6** [comment]
![screenshot_7](https://user-images.githubusercontent.com/9501291/51243435-c44d9980-19ac-11e9-8247-6dd2606ad1a6.png)
Fixed in master
