### ISSUE TITLE
Return 444 for default LE nginx config

### ISSUE THREAD

**Issue by Dilshat** [subutai-io/agent#941]

**Comment by etursunbaev** [comment]
not 404!

**Comment by Dilshat** [comment]
How to test:
On a fresh peer create a port mapping via Bazaar to some domain. The mapping must not use --redirect option.
External port of the mapping must not be equal to 80. There must no exist other mappings for the same domain on port 80.

Result: when opening the domain on port 80 (via http protocol and no port specified in the browser ex: http://thedomain), it must no open. Browser must return message like `The page is not working`

**Comment by Almansherov** [comment]
Followed the instructions from above and met the expected behavior:

![image](https://user-images.githubusercontent.com/32430693/51960496-dacd0980-241e-11e9-8776-80adf63a27e3.png)

**Comment by etursunbaev** [comment]
First approach given by me was wrong that is why it was reopened to fix and test again.
When creating LE https port mapping agent generates default http config file.
`.well-known` section/location is necessary for obtaining LE certificate in this file. For other it should return 444 error code.

I have tested in dev
Agent generated right config file:
```
server {
    listen 80;
    server_name example.com;

	location / {
		return 444;
	}  

    
location /.well-known {                                                                                                                                                                    
	default_type "text/plain";                                                                                                                                                             
	rewrite /.well-known/(.*) /$1 break;                                                                                                                                                   
	root /var/lib/subutai/letsencrypt/webroot/example.com/.well-known/;                                                                                                         
}
}

```
https returns 200
http returns 444

Done in dev.

Need to add other scenarios to test.

**Comment by kurmanbekova6** [comment]
**Scenario 1**
![screenshot from 2019-02-13 10-36-24](https://user-images.githubusercontent.com/9501291/52687295-6a280000-2f7b-11e9-8119-af2b88fe9506.png)
Tested.

@etursunbaev Please, provide the second test case.

**Comment by kurmanbekova6** [comment]
**Scenario 2**
![screenshot from 2019-02-13 12-21-13](https://user-images.githubusercontent.com/9501291/52691063-e45f8100-2f89-11e9-8136-c9c261ffb5cc.png)

**Comment by kurmanbekova6** [comment]
**Scenario 3**
