### ISSUE TITLE
Fix management IP obtainment

### ISSUE THREAD

**Issue by Dilshat** [subutai-io/agent#943]
Management container stopped obtaining IP

**Comment by Dilshat** [comment]
How to test:
1. Create a peer
2. Run on RH `subutai ls i -n management`

Result: management container must have IP 10.10.10.1

**Comment by Almansherov** [comment]
Followed the instructions. Tested:

![image](https://user-images.githubusercontent.com/32430693/51957307-ca159700-2410-11e9-9b45-91212be4fd4f.png)
