### ISSUE TITLE
Implement functionality to manage container snapshots

### ISSUE THREAD

**Issue by Dilshat** [subutai-io/agent#962]
We need to implement CRUD functionality for container snapshots:

- [ ] 1. List snapshots for a specified container
- [ ] 2. Create a snapshot for a specified container and partition (var|opt|home|rootfs), label it
- [ ] 3. Remove a snapshot by label for a specified container and partition
- [ ] 4. Rollback a specified container and partition to a specific snapshot (by its label)

**Comment by Dilshat** [comment]
How to test:
1. Create container **foo**
2. Create a text file with content "Hello World" at path `/var/test.txt` inside container
3. Create a snapshot named **snap** for **var** partition of the container by executing 
```
subutai snapshot create -c foo -p var -l snap
```
4. Check snapshot existence by executing
```
subutai snapshot ls
```
5. Modify file test.txt by changing content to "Hello Bishkek"
6. Rollback container partition **var** to previously created snapshot **snap** by executing:
```
subutai snapshot rollback -c foo -p var -l snap
```
7. Check content of text.txt which must be "Hello World"
8. Remove snapshot by executing
```
subutai snapshot remove -c foo -p var -l snap
```
9. Make sure that snapshot is removed by executing
```
subutai snapshot ls -c foo -p var
```

**Comment by kurmanbekova6** [comment]
On updated peer created container.
Then did the second step.
![screenshot from 2019-02-12 12-40-17](https://user-images.githubusercontent.com/9501291/52616630-5e790280-2ec3-11e9-93b6-a0b6d57d0eee.png)
Tried to create a snapshot
![screenshot from 2019-02-12 12-45-04](https://user-images.githubusercontent.com/9501291/52616835-160e1480-2ec4-11e9-8be6-11b8bc9075b6.png)
@Dilshat Am I doing something wrong? Is this fix on master?

**Comment by kurmanbekova6** [comment]
Followed the steps described above^^
![screenshot from 2019-02-13 10-56-02](https://user-images.githubusercontent.com/9501291/52687948-43b79400-2f7e-11e9-9182-0ef4ba94fce7.png)
![screenshot from 2019-02-13 10-58-00](https://user-images.githubusercontent.com/9501291/52687949-44502a80-2f7e-11e9-8869-af3767da0bfe.png)
Fixed in master
