### ISSUE TITLE
Implement API to dump and restore containers snapshots

### ISSUE THREAD

**Issue by Dilshat** [subutai-io/agent#963]
We want to backup containers to be able to restore them later

**Comment by Dilshat** [comment]
This issue is not clear yet. There are some issues with backup files that needs to be resolved first. Thus it goes to icebox

**Comment by Dilshat** [comment]
We should clearly outline the cases when we need to dump the snapshots to backup files:
1. On the same peer - in this case we don't need to dump snapshots since they are present on the system inside zfs and can be used as is.
2. Recreate container on another peer - in this rare case we should use similar machinery as used for templates: when exporting a template, all its datasets are serialized to delta files and archived into tar.gz file. Then this file is uploaded to central repository (Bazaar CDN). We even can use the same CDN API with an additional flag indicating that this is a container backup. CDN will differentiate based on this flag and provide different serving for such backup archives. Also later on, when peer needs to recreate such a container, it will pull down its archive and recreate the container from it.
However there are a few issues that arise:
- All containers now have static IPs,  we have to deal with that on a new peer where we can not just use the same IP blindly. IP must be assigned from Bazaar and must be unique and reflected in environment metadata
- All containers have unique names in the context of peer. We can not just use the same name as original, so Bazaar must assign such name and update own environment metadata. 
- If new peer has not hosted this environment yet, networking part must be recreated for such container: VLAN, p2p swarm which must be reflected in environment metadata and also adds complexity on Bazaar side

**Comment by Dilshat** [comment]
Additionally we must consider that a backup file is an incremental snapshot between container parent and the time of container backup generation.  Thus, to recreate a container on another peer we must also fulfill the following requirements:
1. Parent template(s) must be present on target peer
2. We need to clone container in a stopped state to exclude any modifications between parent and container filesystem (zfs limitation when receiving snapshots)
3. We need to receive deltas of original container backup to the target container.
4. Start container

**Comment by Dilshat** [comment]
How to test:
1. Create container `subutai clone debian-stretch foo`
2. Create a file inside the container `echo "Hello Subutai" > /var/lib/lxc/foo/var/test.txt`
3. Create a container backup `subutai backup foo`
4. Create a new container using the backup `subutai clone debian-stretch bar --backup /var/cache/subutai/foo.tar.gz`
5. Verify that file _test.txt_ exists `cat /var/lib/lxc/bar/var/test.txt`

**Comment by kurmanbekova6** [comment]
![screenshot from 2019-02-28 11-06-57](https://user-images.githubusercontent.com/9501291/53542506-fd9b2c80-3b48-11e9-8af1-6726f7b80d2b.png)
![screenshot from 2019-02-28 11-06-41](https://user-images.githubusercontent.com/9501291/53542504-fd9b2c80-3b48-11e9-9adf-c8f7769c7b82.png)

Implemented in master
