### ISSUE TITLE
Remove snapshots on container destroy

### ISSUE THREAD

**Issue by Dilshat** [subutai-io/agent#967]
We need to remove all snapshots of container partitions when destroying container. otherwise it prevents container destruction

**Comment by Dilshat** [comment]
How to test:
1. Create container `subutai clone debian-stretch foo`
2. Create snapshots for the container `subutai snap add -c foo -p all -l snap`
3. Make sure snapshots exist `subutai snap ls -c foo`
4. Destroy container `subutai destroy foo`
Result, container foo snapshots must be destroyed too
to verify use `subutai snap ls | grep foo`

**Comment by kurmanbekova6** [comment]
![screenshot from 2019-02-28 10-46-06](https://user-images.githubusercontent.com/9501291/53541916-3554a500-3b46-11e9-83e4-d9bdb9a6d9c7.png)
Tested in master
