### ISSUE TITLE
Do not create forwarding rules for non-environment container

### ISSUE THREAD

**Issue by Dilshat** [subutai-io/agent#968]
Currently iptables rules are created for every container on a peer. We need to exclude all manually created containers since they don't have p2p swarms

**Comment by Dilshat** [comment]
How to test:
1. Create environment via Console/Bazaar
2. Create manually a container `subutai clone debian-stretch foo`
3. After 3 minute check existing iptables rules `iptables -L -t nat | grep DNAT`
Result: existing rules must contain all IPs of environment containers and must not contain IPs of the manually created container

**Comment by kurmanbekova6** [comment]
Followed the steps described above^^
![screenshot from 2019-02-28 17-27-39](https://user-images.githubusercontent.com/9501291/53563429-2e498900-3b7e-11e9-8f6b-3316227c5bce.png)
Fixed in master
