### ISSUE TITLE
Wrong instructions in error message for snapshot rollback command

### ISSUE THREAD

**Issue by samsonbek** [subutai-io/agent#978]
When I tried to rollback container to old snapshot I got error that I have more recent snapshots:
```
root@dhp2:~# subutai snapshot list
NAME                                                 CREATION
subutai/fs/snap1-apache3-uo1-1-3@aaa                 Thu Mar 14  2:16 2019
subutai/fs/snap1-apache3-uo1-1-3@bbb                 Thu Mar 14  2:17 2019
subutai/fs/snap1-apache3-uo1-1-3@ddd                 Thu Mar 14  2:18 2019
root@dhp2:~# 
root@dhp2:~# subutai snapshot rollback --container=snap1-apache3-uo1-1-3 --partition=config --label=bbb
ERRO[2019-03-14 02:20:35] Failed to rollback to snapshotError rolling back to snapshot snap1-apache3-uo1-1-3@bbb: exit status 1: cannot rollback to 'subutai/fs/snap1-apache3-uo1-1-3@bbb': more recent snapshots or bookmarks exist
use '-r' to force deletion of the following snapshots and bookmarks:
subutai/fs/snap1-apache3-uo1-1-3@ddd
 exit status 1 
root@dhp2:~#
```
In error message it said that I should use `-r` to forcibly rollback to old snapshot with ignoring more recent snapshots. But `-r` flag doesn't work:
```
root@dhp2:~# subutai snapshot rollback --container=snap1-apache3-uo1-1-3 --partition=config --label=bbb -r
subutai: error: unknown short flag '-r', try --help
root@dhp2:~#
```
Instead of `-r` I could use `--force` (as written in wiki page here https://github.com/subutai-io/agent/wiki/snapshot):
```
root@dhp2:~# subutai snapshot rollback --container=snap1-apache3-uo1-1-3 --partition=config --label=bbb --force
root@dhp2:~# 
root@dhp2:~# 
root@dhp2:~# subutai snapshot list
NAME                                                 CREATION
subutai/fs/snap1-apache3-uo1-1-3@aaa                 Thu Mar 14  2:16 2019
subutai/fs/snap1-apache3-uo1-1-3@bbb                 Thu Mar 14  2:17 2019\
root@dhp2:~# 
```

So, instructions about `-r` is not consistent with docs.

**Comment by Dilshat** [comment]
How to test:
1. Create a container `subutai clone debian-stretch foo`
2. Create snapshots **a**, **b** and **c** one by one `subutai snap add -c foo -p all -l a; subutai snap add -c foo -p all -l b; subutai snap add -c foo -p all -l c`
3. Try to rollback snapshot **b** `subutai snap rb -c foo -p all -l b`
Result: The command should fail with message
```
Failed to rollback to snapshot Error rolling back to snapshot /foo@b: exit status 1: cannot rollback to 'subutai/fs/foo@b': more recent snapshots or bookmarks exist
use '-f' to force deletion of the following snapshots and bookmarks:
subutai/fs/foo@c
 exit status 1
```
4. Rollback with `--force` option `subutai snap rb -c foo -p all -l b -f`. It should succeed.
5. Check the snapshots of container foo `subutai snap ls -c foo -p home`
Result: only snapshots **a** and **b** must be displayed:
```
NAME                   CREATION
subutai/fs/foo/home@a  Fri Mar 22  3:09 2019
subutai/fs/foo/home@b  Fri Mar 22  3:09 2019
```

**Comment by kurmanbekova6** [comment]
Tested in master
![Screenshot from 2019-03-22 11-39-59](https://user-images.githubusercontent.com/9501291/54802843-4309d000-4c97-11e9-964d-26ca65d6844d.png)
