### ISSUE TITLE
Policy for including seconds precision to snapshot name

### ISSUE THREAD

**Issue by samsonbek** [subutai-io/agent#987]
ZFS provide only up-to-minute precision of snapshot time:
```
root@dhp1:~# subutai snapshot list
NAME                                                 CREATION
subutai/fs/snap1-apache1-ufw-1-5@env-aaa             Wed Mar 27 14:59 2019
subutai/fs/snap1-apache1-ufw-1-5@bbb                 Wed Mar 27 15:00 2019
```
To be able to see more precise time of snapshot creation, we need to append seconds and milliseconds to snapshot name.
So, snapshot name format have to be as following:
`*******-SS-NNN`
where `SS` is seconds, and `NNN` is milliseconds.

So, according to this policy, our example should look like:
```
root@dhp1:~# subutai snapshot list
NAME                                                 CREATION
subutai/fs/snap1-apache1-ufw-1-5@env-aaa-04-235             Wed Mar 27 14:59 2019
subutai/fs/snap1-apache1-ufw-1-5@bbb-59-058                 Wed Mar 27 15:00 2019
```

**Comment by samsonbek** [comment]
Or, even a better way would be, if Agent does this trick with seconds-millis in background, and displays snapshot creation date with that precision, and leave name of snapshot as it is right now, i.e.:
`subutai/fs/snap1-apache1-ufw-1-5@env-aaa`
and 
`subutai/fs/snap1-apache1-ufw-1-5@bbb`

**Comment by samsonbek** [comment]
And, of course unique label constraint should stay in place.

**Comment by Dilshat** [comment]
How to test:
1. Create snapshot for a container `subutai snap add -c foo -p all -l test`
2. List snapshots of the container `subutai snap ls -c foo`

Result: output must container timestamp with miliseconds
e.g.
```
subutai/fs/foo/home@test    2019-04-03T01:30:44.806
```

**Comment by kurmanbekova6** [comment]
![Screenshot from 2019-04-03 10-19-38](https://user-images.githubusercontent.com/9501291/55452580-04aad400-55fa-11e9-9aaa-3ad7c182e3c2.png)
Tested in master
